In [23]:
import numpy as np

In [24]:
array = np.array([1, 2, 3])
array

array([1, 2, 3])

In [25]:
array_divididos = np.split(array, 3)
array_divididos
#divididos em 3 partes

[array([1]), array([2]), array([3])]

In [26]:
for i, value in enumerate(array_divididos):
    print(f"Parte {i+1} ==> {value}")

Parte 1 ==> [1]
Parte 2 ==> [2]
Parte 3 ==> [3]


In [27]:
# Criando uma array 1D com temperaturas diárias de um mês (30 dias)
temperaturas = np.array([30, 32, 31, 29, 28, 30, 31, 32, 33, 34,
                          35, 36, 37, 38, 39, 40, 41, 42, 43,
                          44, 45, 46, 47, 48, 49, 50, 51,
                          52, 53, 54, 55, 56])
temperaturas

array([30, 32, 31, 29, 28, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56])

In [28]:
#Dividindos as temperaturas em 4 semanas
semanas = np.split(temperaturas, 4)
semanas

[array([30, 32, 31, 29, 28, 30, 31, 32]),
 array([33, 34, 35, 36, 37, 38, 39, 40]),
 array([41, 42, 43, 44, 45, 46, 47, 48]),
 array([49, 50, 51, 52, 53, 54, 55, 56])]

In [29]:
for i, value in enumerate (semanas):
    print(f"Semana {i+1} ==> {value}")

Semana 1 ==> [30 32 31 29 28 30 31 32]
Semana 2 ==> [33 34 35 36 37 38 39 40]
Semana 3 ==> [41 42 43 44 45 46 47 48]
Semana 4 ==> [49 50 51 52 53 54 55 56]


In [30]:
medias_semanas = [np.mean(semana) for semana in semanas]
medias_semanas

[np.float64(30.375), np.float64(36.5), np.float64(44.5), np.float64(52.5)]

In [31]:
for i, value in enumerate(medias_semanas):
    print(f"Média da Semana {i+1} ==> {value:.2f}")

Média da Semana 1 ==> 30.38
Média da Semana 2 ==> 36.50
Média da Semana 3 ==> 44.50
Média da Semana 4 ==> 52.50
