In [1]:
import numpy as np

In [2]:
array = np.array ([10, 20, 30, 40, 50])
array

array([10, 20, 30, 40, 50])

In [3]:
# Pesquisar a posição valor 30
posicao = np.where(array == 30)
posicao

(array([2]),)

In [4]:
#Criar um array com notas de alunos
notas = np.array([7.5, 8.0, 9.0, 6.5, 10.0, 8.5])
notas

array([ 7.5,  8. ,  9. ,  6.5, 10. ,  8.5])

In [5]:
#Pesquisar quais alunos foram aprovados (nota > 6.0)
aprovados = np.where(notas > 6.0)
aprovados
#Traz indices

(array([0, 1, 2, 3, 4, 5]),)

In [ ]:
notas[aprovados] #Traz notas dos alunos aprovados
#sem o uso do where

array([ 7.5,  8. ,  9. ,  6.5, 10. ,  8.5])

In [ ]:
nota_maxima = np.max(notas) #Traz a maior nota
nota_maxima

In [ ]:
indice_maximo = np.argmax(notas) #Traz o indice da maior nota
indice_maximo