In [13]:
import numpy as np

In [14]:
array_1d = np.array([1, 2, 3])
print(array_1d.ndim) # 1 dimensão
print (array_1d.shape) # 3 elementos
array_1d
# Lista de dados, como séries temporais ou coleção de valores

1
(3,)


array([1, 2, 3])

In [15]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim) # 2 dimensões
print (array_2d.shape) # 2 linhas e 3 colunas
array_2d
#matrizes, vetores, tensores, tabela de dados, imagens em escalas

2
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
array_3d = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(array_3d.ndim) # 3 dimensões, porque é uma lista de listas de listas
print (array_3d.shape)# 1 camada, 4 linhas e 2 colunas
array_3d
#imagens em cores(cada matriz representando um canal de cor, com RGB)

3
(1, 4, 2)


array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [17]:
array_4d = np.zeros ((2, 3, 4, 5))
print(array_4d.ndim) # 4 dimensões
print (array_4d.shape) # 2 linhas, 3 colunas, 4 profundidade e 5 canais
array_4d

4
(2, 3, 4, 5)


array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])