In [16]:
import numpy as np

In [25]:
array = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
print(array.ndim) #2
print(array.shape) #(3, 3)
array

2
(3, 3)


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [18]:
#buscar elemento na linha 1 e coluna 2, lembrando que começa em 0
elemento = array[1, 2]
elemento

np.int64(60)

In [19]:
#Pegar dados da primeira linha
linha_0 = array[0]
linha_0

array([10, 20, 30])

In [20]:
#Acessando a coluna 1
coluna_1 = array[:, 1]#:,significa todas as linhas e a coluna 1
coluna_1

array([20, 50, 80])

In [21]:
#Fatiando para obter um subarray
subarray = array[0:2, 1:3]#linhas 0 e 1 e colunas 1 e 2
subarray

array([[20, 30],
       [50, 60]])

In [22]:
#mascar o valor de um elemento
mascara = array > 50
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [23]:
#Acessando os elementos maiores que 50
elementos_maiores_50 = array[mascara]
elementos_maiores_50

array([60, 70, 80, 90])

In [24]:
#Modificando elemento na linha 1, coluna 1
array[1, 1] = 100 #modificar 50 para 100
array

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])