In [28]:
#Funções

In [29]:
import numpy as np

In [30]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [31]:
# 1. Soma de todos os elementos do array
soma = np.add(array, 5)
soma

array([ 6,  7,  8,  9, 10])

In [32]:
#2. Função para subtrair dois arrays
subtracao = np.subtract(array, 5)
subtracao

array([-4, -3, -2, -1,  0])

In [33]:
#3. Função para multiplicar dois arrays
multiplicacao = np.multiply(array, 2)
multiplicacao

array([ 2,  4,  6,  8, 10])

In [34]:
#4. Divisão de dois arrays
divisao = np.divide(array, 2)
divisao

array([0.5, 1. , 1.5, 2. , 2.5])

In [35]:
#5. Funções trigonométricas que é o seno
seno = np.sin(array)
seno

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [36]:
#6. Função consseno
cosseno = np.cos(array)
cosseno

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [37]:
#7 Fução estatística média
media = np.mean(array)
media

np.float64(3.0)

In [38]:
#8. Função desvio padrão
desvio_padrao = np.std(array)
desvio_padrao

np.float64(1.4142135623730951)

In [39]:
#9. Funções de comparação
comparacao_maior_que_3 = array > 3
comparacao_maior_que_3

array([False, False, False,  True,  True])

In [40]:
#10. Combinando Funções
resultado = np.sqrt(array) + np.power(array, 2)# sqrt é raiz quadrada e power é potência
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])

In [41]:
#11. Funções exponenciais
exponencial = np.exp(array)
exponencial

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [42]:
#12. Funções logarítmicas
logaritmo = np.log(array)
logaritmo

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [43]:
#13. Função de arrendondamento
arrendondar = np.round(array, 2)
arrendondar

array([1, 2, 3, 4, 5])

In [44]:
#14. Função de Potência 
potencia = np.power(array, 3)#ao cubo
potencia

array([  1,   8,  27,  64, 125])