In [76]:
import numpy as np

In [77]:
# Criando dois arrays 1D

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [78]:
#Concatenando os arrays 1D
novo_array = np.concatenate((array1, array2))
array2

array([4, 5, 6])

In [79]:
#Criando arrays para nomes e notas
nomes = np.array(['Ana', 'Beto', 'Carlos'])
notas_matematica = np.array([7.5, 8.0, 9.0])
notas_fisica = np.array([6.5, 7.0, 8.5])


In [80]:
#Usando np.stack para empilhar verticalmente os dados
dados_estudantes = np.vstack((nomes, notas_matematica, notas_fisica))
dados_estudantes

array([['Ana', 'Beto', 'Carlos'],
       ['7.5', '8.0', '9.0'],
       ['6.5', '7.0', '8.5']], dtype='<U32')

In [81]:
# Usando o np.staskck para empilhar horizontalmente os dados
matriz_notas = np.column_stack((notas_matematica, notas_fisica))
matriz_notas                       

array([[7.5, 6.5],
       [8. , 7. ],
       [9. , 8.5]])

In [82]:
# Adicionando colunar com a média das notas
media_notas = np.mean(matriz_notas, axis=1)
matriz_notas = np.column_stack((matriz_notas, media_notas))
matriz_notas

array([[7.5 , 6.5 , 7.  ],
       [8.  , 7.  , 7.5 ],
       [9.  , 8.5 , 8.75]])