Copy 
  - Uma nova cópia do array é criada em memória
Isso significa que as 2 matrizes são idenpendentes uma da outra
Matriz Original e a Cópia.

View
-  Não é criada em uma nova cópia da memória.
A view compartilha os mesmos dados que o array original.


In [26]:
import numpy as np

In [27]:
array_orig = np.array([[1, 2, 3], 
                       [4, 5, 6],
                       [7, 8, 9]])
array_orig

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
# 1- Cópia Rasa (view)
array_view = array_orig[1:, 1:]
array_view


array([[5, 6],
       [8, 9]])

In [29]:
array_view[0, 0] = 99
array_view

array([[99,  6],
       [ 8,  9]])

In [30]:
array_orig

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [31]:
#2. Cópia Profunda (Copy)
array_cop = array_orig.copy()
array_cop

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [32]:
array_cop[0, 0] = 100
array_orig

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [33]:
array_cop

array([[100,   2,   3],
       [  4,  99,   6],
       [  7,   8,   9]])